const CURRENT_SEASON_ID = '2026_q2_orion';

const SEASON_DB = {
    "2026_q2_orion": {
        id: "2026_q2_orion",
        name: "Orion Anomaly Season (2026 Q2)",
        cardEnabled: true,
        badgePath: "static/orion/",
        endTime: "2026-06-30T23:59:59",
        tiers: [
            { name: 'Bronze', value: 5000, color: 'rgba(205,127,50,0.5)' },
            { name: 'Silver', value: 8000, color: 'rgba(192,192,192,0.5)' },
            { name: 'Gold', value: 15000, color: 'rgba(255,215,0,0.5)' },
            { name: 'Platinum', value: 25000, color: 'rgba(229,228,226,0.5)' }
        ],
        activities: [
            { id: 'bounties', nameKey: 'act_bounties', descKey: 'desc_bounties', max: 6720, unit: 'tokens', isBounty: true },
            { id: 'ifs_apr', nameKey: 'act_ifs_apr', descKey: 'desc_ifs_apr', max: 2500, unit: 'tokens' },
            { id: 'ifs_may', nameKey: 'act_ifs_may', descKey: 'desc_ifs_may', max: 2500, unit: 'tokens' },
            { id: 'ifs_jun', nameKey: 'act_ifs_jun', descKey: 'desc_ifs_jun', max: 2500, unit: 'tokens' },
            { id: 'op_sakura', nameKey: 'act_op_sakura', utcStart: '2026-04-07T18:00:00Z', utcEnd: '2026-04-30T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'op_global', nameKey: 'act_op_global', utcStart: '2026-04-24T18:00:00Z', utcEnd: '2026-05-12T18:00:00Z', max: 7500, unit: 'tokens' },
            { id: 'op_may_early', nameKey: 'act_op_may_early', utcStart: '2026-05-01T18:00:00Z', utcEnd: '2026-06-01T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'op_may_late', nameKey: 'act_op_may_late', utcStart: '2026-05-22T18:00:00Z', utcEnd: '2026-06-02T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'op_solstice', nameKey: 'act_op_solstice', utcStart: '2026-06-05T18:00:00Z', utcEnd: '2026-06-22T18:00:00Z', max: 3000, unit: 'tokens' },
            { id: 'anomaly', nameKey: 'act_anomaly', descKey: 'desc_anomaly', max: 30000, unit: 'tokens' }
        ],
        i18n: {
            zh: {
                pageTitle: 'ORION 赛季计划工具',
                pageSubtitle: '2026 Q2 (4/8 - 6/30)',
                footerSource: '来源：Ingress 2026 Q2 Orion 赛季说明。所有输入数据均在本地浏览器存储。',
                act_bounties: '每日任务 (Daily Bounties)',
                act_ifs_apr: 'IFS - 四月',
                act_ifs_may: 'IFS - 五月',
                act_ifs_jun: 'IFS - 六月',
                act_op_sakura: 'Dispatch: 樱花祭',
                act_op_global: 'Orion 全球行动',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: 夏至',
                act_anomaly: 'Anomaly 现场行动',
                desc_bounties: '4/8 - 6/30 (84天), 每天满额 80 tokens',
                desc_ifs_apr: '4/4 现场活动',
                desc_ifs_may: '5/2 现场活动',
                desc_ifs_jun: '6/6 现场活动',
                desc_anomaly: '单站最高 5000 tokens',
                max_anomaly: '5000 x 场次',
            },
            en: {
                pageTitle: 'ORION SEASON PLANNER',
                pageSubtitle: '2026 Q2 (Apr 8 - Jun 30)',
                footerSource: 'Source: Ingress 2026 Q2 Orion Season. All data is stored locally in this browser.',
                act_bounties: 'Daily Bounties',
                act_ifs_apr: 'IFS - April',
                act_ifs_may: 'IFS - May',
                act_ifs_jun: 'IFS - June',
                act_op_sakura: 'Dispatch: Sakura Festival',
                act_op_global: 'Orion Global Operation',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: Summer Solstice',
                act_anomaly: 'Anomaly On-site',
                desc_bounties: 'Apr 8 - Jun 30 (84 days), up to 80 tokens/day',
                desc_ifs_apr: 'Apr 4 on-site event',
                desc_ifs_may: 'May 2 on-site event',
                desc_ifs_jun: 'Jun 6 on-site event',
                desc_anomaly: 'Up to 5000 tokens per site',
                max_anomaly: '5000 x #sites',
            },
            ja: {
                pageTitle: 'ORION シーズンプランナー',
                pageSubtitle: '2026 Q2 (4/8 - 6/30)',
                footerSource: '出典：Ingress 2026 Q2 Orion シーズン説明。すべてのデータはブラウザにローカル保存されます。',
                act_bounties: 'デイリーバウンティ',
                act_ifs_apr: 'IFS - 4月',
                act_ifs_may: 'IFS - 5月',
                act_ifs_jun: 'IFS - 6月',
                act_op_sakura: 'Dispatch: 桜まつり',
                act_op_global: 'Orion グローバルオペレーション',
                act_op_may_early: 'Nemesis Redux: Myriad',
                act_op_may_late: 'Hank Johnson: The Courier Files',
                act_op_solstice: 'Dispatch: 夏至',
                act_anomaly: 'XMアノマリー',
                desc_bounties: '4/8 - 6/30 (84日間), 1日最大 80 tokens',
                desc_ifs_apr: '4/4 現地イベント',
                desc_ifs_may: '5/2 現地イベント',
                desc_ifs_jun: '6/6 現地イベント',
                desc_anomaly: '1サイト最大 5000 tokens',
                max_anomaly: '5000 x サイト数',
            }
        }
    }
};
